# Generated by Django 4.1.2 on 2023-10-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Register_Login", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="height",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="subscription_deadline",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="subscription_type",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="weight",
        ),
    ]
