# Generated by Django 4.1.2 on 2023-10-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Register_Login", "0002_remove_profile_goal_remove_profile_height_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="is_staff",
            new_name="is_nurse",
        ),
    ]
