# Generated by Django 4.1.2 on 2023-10-08 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nurse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=30, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("document_01", models.CharField(blank=True, max_length=30, null=True)),
                ("document_02", models.CharField(blank=True, max_length=30, null=True)),
                ("document_03", models.CharField(blank=True, max_length=30, null=True)),
                ("national_id", models.CharField(blank=True, max_length=50, null=True)),
                ("published", models.BooleanField(default=False)),
                ("pending", models.BooleanField(default=False)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nurse",
                "verbose_name_plural": "Nurses",
            },
        ),
    ]
