# Generated by Django 4.1.2 on 2023-10-08 18:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Nurse", "0001_initial"),
        ("Bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bookings",
            new_name="Booking",
        ),
    ]
