# Generated by Django 4.1.2 on 2023-10-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0002_rename_bookings_booking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"verbose_name": "Booking", "verbose_name_plural": "Bookings"},
        ),
    ]
